# Generated by Django 2.0.5 on 2018-05-21 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=400)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DossierSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_text', models.TextField()),
                ('order', models.PositiveSmallIntegerField()),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecosyn.Dossier')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, max_length=300)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='ecosyn/pictures/')),
                ('height', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('width', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=400)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('caused_by', models.ManyToManyField(blank=True, related_name='cause_set', to='ecosyn.Sujet')),
                ('consequence', models.ManyToManyField(blank=True, related_name='consequence_set', to='ecosyn.Sujet')),
                ('header_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujet_header', to='ecosyn.Picture')),
                ('left_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujet_left', to='ecosyn.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='SujetSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_text', models.TextField()),
                ('order', models.PositiveSmallIntegerField()),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecosyn.Picture')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecosyn.Sujet')),
            ],
        ),
        migrations.AddField(
            model_name='dossiersection',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecosyn.Picture'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='header_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier_header', to='ecosyn.Picture'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='left_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier_left', to='ecosyn.Picture'),
        ),
    ]
