# Generated by Django 2.0.5 on 2018-05-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiersection',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_set', to='ecosyn.Dossier'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='sujetsection',
            name='sujet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_set', to='ecosyn.Sujet'),
        ),
    ]
