# Generated by Django 2.0.5 on 2018-05-21 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0002_auto_20180521_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='height',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='width',
        ),
        migrations.RemoveField(
            model_name='sujet',
            name='consequence',
        ),
        migrations.AlterField(
            model_name='dossier',
            name='header_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ecosyn.Picture'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='left_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ecosyn.Picture'),
        ),
        migrations.AlterField(
            model_name='dossiersection',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ecosyn.Picture'),
        ),
        migrations.AlterField(
            model_name='sujet',
            name='caused_by',
            field=models.ManyToManyField(blank=True, related_name='consequence', to='ecosyn.Sujet'),
        ),
        migrations.AlterField(
            model_name='sujet',
            name='header_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ecosyn.Picture'),
        ),
        migrations.AlterField(
            model_name='sujet',
            name='left_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ecosyn.Picture'),
        ),
        migrations.AlterField(
            model_name='sujetsection',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ecosyn.Picture'),
        ),
    ]
