# Generated by Django 2.0.5 on 2018-05-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0003_auto_20180521_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='sujet',
            old_name='left_picture',
            new_name='icon_picture',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='left_picture',
        ),
        migrations.AddField(
            model_name='sujet',
            name='sector',
            field=models.ManyToManyField(to='ecosyn.Sector'),
        ),
    ]
