# Generated by Django 2.0.5 on 2018-05-25 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0004_auto_20180524_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='icon_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ecosyn.Picture'),
        ),
        migrations.AddField(
            model_name='sujet',
            name='icon_graph_height',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='sujet',
            name='icon_size',
            field=models.IntegerField(blank=True, default=20),
        ),
    ]
