# Generated by Django 2.0.5 on 2018-06-06 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0005_auto_20180525_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_share', models.FloatField(blank=True, default=None)),
                ('description', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='sujet',
            name='caused_by',
        ),
        migrations.AddField(
            model_name='dossiersection',
            name='opinion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='color',
            field=models.CharField(default='grey', max_length=50),
        ),
        migrations.AddField(
            model_name='sujetsection',
            name='opinion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sector',
            name='icon_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Topics', to='ecosyn.Picture'),
        ),
        migrations.AddField(
            model_name='lien',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consequences', to='ecosyn.Sujet'),
        ),
        migrations.AddField(
            model_name='lien',
            name='consequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Causes', to='ecosyn.Sujet'),
        ),
    ]
