# Generated by Django 2.0.5 on 2018-06-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0006_auto_20180606_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lien',
            old_name='description',
            new_name='cause_description',
        ),
        migrations.AddField(
            model_name='lien',
            name='consequence_description',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
