# Generated by Django 2.0.5 on 2018-06-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0008_auto_20180608_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sujet',
            name='icon_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sujet',
            name='icon_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sujet',
            name='icon_size',
            field=models.FloatField(blank=True, default=20),
        ),
    ]
