# Generated by Django 2.0.5 on 2018-06-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0009_auto_20180609_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sujet',
            name='icon_graph_height',
        ),
    ]
