# Generated by Django 2.0.5 on 2018-06-10 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0010_remove_sujet_icon_graph_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrowBreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.FloatField()),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('liens', models.ManyToManyField(to='ecosyn.Lien')),
            ],
        ),
        migrations.CreateModel(
            name='GraphArrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrows', to='ecosyn.Graph')),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=400)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('color', models.CharField(default='grey', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('header_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ecosyn.Picture')),
                ('icon_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Topics', to='ecosyn.Picture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecteurSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_text', models.TextField()),
                ('order', models.PositiveSmallIntegerField()),
                ('opinion', models.BooleanField(default=False)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ecosyn.Picture')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_set', to='ecosyn.Secteur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='header_picture',
        ),
        migrations.RemoveField(
            model_name='dossiersection',
            name='dossier',
        ),
        migrations.RemoveField(
            model_name='dossiersection',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='icon_picture',
        ),
        migrations.RemoveField(
            model_name='sujet',
            name='sector',
        ),
        migrations.AlterField(
            model_name='sujet',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Dossier',
        ),
        migrations.DeleteModel(
            name='DossierSection',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.AddField(
            model_name='graph',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecosyn.Secteur'),
        ),
        migrations.AddField(
            model_name='arrowbreak',
            name='arrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakpoints', to='ecosyn.GraphArrow'),
        ),
        migrations.AddField(
            model_name='sujet',
            name='Secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecosyn.Secteur'),
        ),
    ]
