# Generated by Django 2.0.5 on 2018-06-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0014_auto_20180610_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='section',
        ),
        migrations.RemoveField(
            model_name='illustration',
            name='content',
        ),
        migrations.AddField(
            model_name='illustration',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='ecosyn.Section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='section',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
