# Generated by Django 2.0.5 on 2018-06-10 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0015_auto_20180610_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrowbreak',
            name='arrow',
        ),
        migrations.RemoveField(
            model_name='grapharrow',
            name='node1',
        ),
        migrations.RemoveField(
            model_name='grapharrow',
            name='node2',
        ),
        migrations.AddField(
            model_name='grapharrow',
            name='X0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grapharrow',
            name='X1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grapharrow',
            name='Y0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grapharrow',
            name='Y1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grapharrow',
            name='cause',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ecosyn.Sujet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grapharrow',
            name='consequence',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ecosyn.Sujet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grapharrow',
            name='illustration',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='arrows', to='ecosyn.Illustration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graphnode',
            name='illustration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='ecosyn.Illustration'),
        ),
        migrations.DeleteModel(
            name='ArrowBreak',
        ),
    ]
