# Generated by Django 2.0.5 on 2018-06-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0017_auto_20180610_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='illustration',
            name='name',
            field=models.CharField(default='Illustration', max_length=50),
        ),
        migrations.AlterField(
            model_name='graphnode',
            name='liens',
            field=models.ManyToManyField(blank=True, to='ecosyn.Lien'),
        ),
    ]
