# Generated by Django 2.0.5 on 2018-06-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0018_auto_20180610_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturedim',
            name='bottom',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='picturedim',
            name='height',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='picturedim',
            name='left',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='picturedim',
            name='right',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='picturedim',
            name='top',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='picturedim',
            name='width',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
