# Generated by Django 2.0.5 on 2018-06-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0019_auto_20180610_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphnode',
            name='liens',
        ),
        migrations.AddField(
            model_name='illustration',
            name='liens',
            field=models.ManyToManyField(blank=True, to='ecosyn.Lien'),
        ),
    ]
