# Generated by Django 2.0.5 on 2018-06-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0020_auto_20180610_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustration',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='width',
            field=models.IntegerField(),
        ),
    ]
