# Generated by Django 2.0.5 on 2018-06-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0021_auto_20180610_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sujet',
            old_name='Secteur',
            new_name='secteur',
        ),
    ]
