# Generated by Django 2.0.5 on 2018-06-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0022_auto_20180610_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illustration',
            name='liens',
        ),
        migrations.AddField(
            model_name='graphnode',
            name='liens',
            field=models.ManyToManyField(blank=True, to='ecosyn.Lien'),
        ),
    ]
