# Generated by Django 2.0.5 on 2018-06-11 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0023_auto_20180611_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grapharrow',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ecosyn.GraphNode'),
        ),
        migrations.AlterField(
            model_name='grapharrow',
            name='consequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ecosyn.GraphNode'),
        ),
    ]
