# Generated by Django 2.0.5 on 2018-06-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0024_auto_20180611_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
