# Generated by Django 2.0.5 on 2018-06-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0025_auto_20180612_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illustration',
            name='section',
        ),
        migrations.AddField(
            model_name='illustration',
            name='section',
            field=models.ManyToManyField(related_name='illustrations', to='ecosyn.Section'),
        ),
    ]
