# Generated by Django 2.0.5 on 2018-06-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosyn', '0027_picture_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustration',
            name='position',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('LT', 'Left Top'), ('RT', 'Right Top'), ('LB', 'Left Bottom'), ('RB', 'Right Bottom'), ('BR', 'Bottom Right'), ('BL', 'Bottom Left'), ('BC', 'Bottom Center')], default='L', max_length=2),
        ),
    ]
